/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import beerexceptions.ImposibleBeer;
import beerstyles.Beer;
import beerstyles.Beer_Styles;
import ingredients.Ingredient;
import ingredients.Ingredients;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ernsferrari
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        initialiceComponents();
        this.setTitle("Beer Styles");
        
        this.ayudajTextArea.setText("Bienvenido al programa Beer Style, tu ayudante en los estilos de cerveza. En esta ayuda comenzaremos por aclarar algunos nombres de las variables de entrada.\n\n" +
            "- SRM (Standard Reference Method): indica el color de la cerveza, para ello se realiza la medición de la atenuación de un haz de luz de longitud con onda igual a 430 nm al pasar a través de 1 cm de cerveza. Dicha atenuación se expresa como una absorción, la cual es escalada mediante una constante igual a 12,7.\n" +
            "- IBU (International Bitterness Unit): es la medida utilizada para indicar la cantidad de miligramos de iso-alfa-ácidos presentes por cada litro de cerveza.\n" +
            "- Densidad Original: esta variable se corresponde con la densidad del mosto (antes de producirse la fermentación).\n" +
            "- Densidad Final: esta variable se corresponde con la densidad de la cerveza (despues de producirse la fermentación).\n" +
            "- Transparencia: si la cerveza es turbia o, por el contrario, transparente.\n" +
            "- Fermentación: variable que indica si la cerveza se ha fermentado con levadura de alta o baja fermentación.\n" +
            "- Ingredientes: está compuesto por un conjunto de campos correspondiéndose con ingredientes atípicos que influyen en el estilo de la cerveza. En el caso del trigo, del centeno y del arroz/maíz los valores a introducir son porcentajes, mientras que en el resto es indicar si están o no.\n" +
            "- Aroma / Sabor Primario y Secundario: son los dos aromas o sabores característicos de la cerveza. Los distintos valores son una abstracción de otros, por ejemplo, el valor cereal incluye a su vez los frutos secos, el pan y la galleta.\n" +
            "\n" +
            "\n" +
            "El uso del programa es el siguiente:\n" +
            "Introduzca el valor correspondiente a cada una de las entradas, con la particularidad de que cuando seleccione el porcentaje de cada ingrediente, no se supere el 100% en conjunto (ejemplo: trigo = 50%, centeno = 20%, arroz/maíz = 0%, su suma será igual al 70%, no supera el 100%, por lo que resulta válido). El porcentaje restante corresponderá con malta de cebada. Otra particularidad es que en los aromas/sabores, no se puede repetir el mismo valor.\n" +
            "Una vez ha completado todos los campos presione el botón \"Aceptar\" para conocer el estilo de la cerveza. Para regresar a la pantalla principal presione el botón \"Regresar\".\n" +
            "Si desease reiniciar los campos ha de seleccionar el  botón \"Restablecer\".");
        
        aroma_sabor_2ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fruta (tropical, citricos...)", "Herbal", "Humo/Quemado", "Cafe", "Cacao", "Caramelo", "Cereal", "Fruta (ciruela, uva...)", "Especias", "Mineral", "Acido" }));
        aroma_sabor_1ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fruta (tropical, citricos...)", "Herbal", "Humo/Quemado", "Cafe", "Cacao", "Caramelo", "Cereal", "Fruta (ciruela, uva...)", "Especias", "Mineral", "Acido" }));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ibuSlider = new javax.swing.JSlider();
        ogSlider = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fgSlider = new javax.swing.JSlider();
        jpanel0 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        trigoSlider = new javax.swing.JSlider();
        jLabel18 = new javax.swing.JLabel();
        centenoSlider = new javax.swing.JSlider();
        arroz_maizSlider = new javax.swing.JSlider();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        especiasComboBox = new javax.swing.JComboBox();
        unhoppedComboBox = new javax.swing.JComboBox();
        trigoJTextField = new javax.swing.JTextField();
        centenoJTextField = new javax.swing.JTextField();
        arroz_maizJTextField = new javax.swing.JTextField();
        ibuJTextField = new javax.swing.JTextField();
        ogJTextField = new javax.swing.JTextField();
        fgJTextField = new javax.swing.JTextField();
        transparenciaComboBox = new javax.swing.JComboBox();
        fermentacionComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        colorSlider = new javax.swing.JSlider();
        colorJTextField = new javax.swing.JTextField();
        aroma_sabor_2ComboBox = new javax.swing.JComboBox();
        aroma_sabor_1ComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        aceptarButton = new javax.swing.JButton();
        restablecerButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ayudajTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setPreferredSize(new java.awt.Dimension(526, 650));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("IBU");

        jLabel4.setText("Transparencia");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Fermentación");

        jLabel6.setBackground(new java.awt.Color(227, 227, 227));
        jLabel6.setText("Ingredientes");
        jLabel6.setOpaque(true);

        ibuSlider.setMajorTickSpacing(1);
        ibuSlider.setMaximum(120);
        ibuSlider.setMinimum(1);
        ibuSlider.setValue(1);
        ibuSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ibuSliderMouseDragged(evt);
            }
        });
        ibuSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ibuSliderMouseClicked(evt);
            }
        });

        ogSlider.setMaximum(1150);
        ogSlider.setMinimum(1030);
        ogSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ogSliderMouseDragged(evt);
            }
        });
        ogSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ogSliderMouseClicked(evt);
            }
        });

        jLabel9.setText("Densidad Original");

        jLabel10.setText("Densidad Final");

        fgSlider.setMaximum(1060);
        fgSlider.setMinimum(1000);
        fgSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                fgSliderMouseDragged(evt);
            }
        });
        fgSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fgSliderMouseClicked(evt);
            }
        });

        jpanel0.setBackground(new java.awt.Color(227, 227, 227));

        jLabel17.setText("Trigo");

        trigoSlider.setValue(0);
        trigoSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                trigoSliderMouseDragged(evt);
            }
        });
        trigoSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trigoSliderMouseClicked(evt);
            }
        });

        jLabel18.setText("Centeno");

        centenoSlider.setValue(0);
        centenoSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                centenoSliderMouseDragged(evt);
            }
        });
        centenoSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                centenoSliderMouseClicked(evt);
            }
        });

        arroz_maizSlider.setValue(0);
        arroz_maizSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                arroz_maizSliderMouseDragged(evt);
            }
        });
        arroz_maizSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arroz_maizSliderMouseClicked(evt);
            }
        });

        jLabel19.setText("Arroz y/o Maíz");

        jLabel20.setText("¿Sin lúpulo?");

        jLabel21.setText("Especias u otros ingrdientes");

        especiasComboBox.setBackground(new java.awt.Color(227, 227, 227));
        especiasComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));
        especiasComboBox.setSelectedIndex(1);
        especiasComboBox.setOpaque(true);

        unhoppedComboBox.setBackground(new java.awt.Color(227, 227, 227));
        unhoppedComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));
        unhoppedComboBox.setSelectedIndex(1);
        unhoppedComboBox.setOpaque(true);

        trigoJTextField.setEditable(false);
        trigoJTextField.setBackground(new java.awt.Color(0, 0, 0));
        trigoJTextField.setForeground(new java.awt.Color(255, 255, 255));
        trigoJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        trigoJTextField.setFocusable(false);
        trigoJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trigoJTextFieldActionPerformed(evt);
            }
        });

        centenoJTextField.setEditable(false);
        centenoJTextField.setBackground(new java.awt.Color(0, 0, 0));
        centenoJTextField.setForeground(new java.awt.Color(255, 255, 255));
        centenoJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        centenoJTextField.setFocusable(false);
        centenoJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centenoJTextFieldActionPerformed(evt);
            }
        });

        arroz_maizJTextField.setEditable(false);
        arroz_maizJTextField.setBackground(new java.awt.Color(0, 0, 0));
        arroz_maizJTextField.setForeground(new java.awt.Color(255, 255, 255));
        arroz_maizJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        arroz_maizJTextField.setFocusable(false);
        arroz_maizJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arroz_maizJTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel0Layout = new javax.swing.GroupLayout(jpanel0);
        jpanel0.setLayout(jpanel0Layout);
        jpanel0Layout.setHorizontalGroup(
            jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel0Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addGroup(jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel0Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(especiasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unhoppedComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))
                    .addGroup(jpanel0Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(trigoSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(centenoSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arroz_maizSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trigoJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(centenoJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arroz_maizJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jpanel0Layout.setVerticalGroup(
            jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel0Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(trigoJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(trigoSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(centenoSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(centenoJTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(arroz_maizSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arroz_maizJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(unhoppedComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(especiasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ibuJTextField.setEditable(false);
        ibuJTextField.setBackground(new java.awt.Color(0, 0, 0));
        ibuJTextField.setForeground(new java.awt.Color(255, 255, 255));
        ibuJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ibuJTextField.setFocusable(false);
        ibuJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibuJTextFieldActionPerformed(evt);
            }
        });

        ogJTextField.setEditable(false);
        ogJTextField.setBackground(new java.awt.Color(0, 0, 0));
        ogJTextField.setForeground(new java.awt.Color(255, 255, 255));
        ogJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ogJTextField.setFocusable(false);
        ogJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ogJTextFieldActionPerformed(evt);
            }
        });

        fgJTextField.setEditable(false);
        fgJTextField.setBackground(new java.awt.Color(0, 0, 0));
        fgJTextField.setForeground(new java.awt.Color(255, 255, 255));
        fgJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fgJTextField.setFocusable(false);
        fgJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fgJTextFieldActionPerformed(evt);
            }
        });

        transparenciaComboBox.setBackground(new java.awt.Color(255, 255, 255));
        transparenciaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Transparente", "Turbia" }));
        transparenciaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transparenciaComboBoxActionPerformed(evt);
            }
        });

        fermentacionComboBox.setBackground(new java.awt.Color(255, 255, 255));
        fermentacionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alta", "Baja" }));
        fermentacionComboBox.setOpaque(true);
        fermentacionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermentacionComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Color (SRM)");

        colorSlider.setMajorTickSpacing(1);
        colorSlider.setMaximum(40);
        colorSlider.setMinimum(1);
        colorSlider.setValue(1);
        colorSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        colorSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                colorSliderMouseDragged(evt);
            }
        });
        colorSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorSliderMouseClicked(evt);
            }
        });

        colorJTextField.setEditable(false);
        colorJTextField.setBackground(new java.awt.Color(0, 0, 0));
        colorJTextField.setForeground(new java.awt.Color(255, 255, 255));
        colorJTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        colorJTextField.setFocusable(false);
        colorJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorJTextFieldActionPerformed(evt);
            }
        });

        aroma_sabor_2ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        aroma_sabor_2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aroma_sabor_2ComboBoxActionPerformed(evt);
            }
        });

        aroma_sabor_1ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        aroma_sabor_1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aroma_sabor_1ComboBoxActionPerformed(evt);
            }
        });

        jLabel7.setText("Aroma / Sabor Primario");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Aroma / Sabor Secundario");

        jPanel1.setBackground(new java.awt.Color(227, 227, 227));

        aceptarButton.setText("Aceptar");
        aceptarButton.setPreferredSize(new java.awt.Dimension(116, 29));
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        restablecerButton.setText("Restablecer");
        restablecerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restablecerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(restablecerButton)
                .addGap(130, 130, 130))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restablecerButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(transparenciaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ogSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ibuSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fgSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(colorSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ibuJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ogJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fgJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(colorJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(fermentacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(23, 23, 23))))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(aroma_sabor_1ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aroma_sabor_2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7)
                    .addComponent(jpanel0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(colorSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colorJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ibuSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ibuJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ogSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ogJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fgSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fgJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(transparenciaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fermentacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jpanel0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(aroma_sabor_1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(aroma_sabor_2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel8)))
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        colorSlider.getAccessibleContext().setAccessibleName("");

        jTabbedPane2.addTab("¿Qué estilo es? ", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        ayudajTextArea.setBackground(new java.awt.Color(227, 227, 227));
        ayudajTextArea.setColumns(20);
        ayudajTextArea.setLineWrap(true);
        ayudajTextArea.setRows(5);
        ayudajTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(ayudajTextArea);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Ayuda", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fgJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fgJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fgJTextFieldActionPerformed

    private void ogJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ogJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ogJTextFieldActionPerformed

    private void ibuJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibuJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ibuJTextFieldActionPerformed

    private void transparenciaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transparenciaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transparenciaComboBoxActionPerformed

    private void fermentacionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermentacionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fermentacionComboBoxActionPerformed

    private void colorJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorJTextFieldActionPerformed

    private void trigoJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trigoJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trigoJTextFieldActionPerformed

    private void centenoJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centenoJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_centenoJTextFieldActionPerformed

    private void arroz_maizJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arroz_maizJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arroz_maizJTextFieldActionPerformed

    private void aroma_sabor_2ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aroma_sabor_2ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aroma_sabor_2ComboBoxActionPerformed

    private void aroma_sabor_1ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aroma_sabor_1ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aroma_sabor_1ComboBoxActionPerformed

    private void colorSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorSliderMouseDragged
        colorJTextField.setText(Integer.toString(colorSlider.getValue()));
    }//GEN-LAST:event_colorSliderMouseDragged

    private void ibuSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ibuSliderMouseDragged
        ibuJTextField.setText(Integer.toString(ibuSlider.getValue()));
    }//GEN-LAST:event_ibuSliderMouseDragged

    private void ogSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ogSliderMouseDragged
        ogJTextField.setText(Integer.toString(ogSlider.getValue()));
    }//GEN-LAST:event_ogSliderMouseDragged

    private void trigoSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trigoSliderMouseDragged
        trigoJTextField.setText(Integer.toString(trigoSlider.getValue()));
    }//GEN-LAST:event_trigoSliderMouseDragged

    private void centenoSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_centenoSliderMouseDragged
        centenoJTextField.setText(Integer.toString(centenoSlider.getValue()));
    }//GEN-LAST:event_centenoSliderMouseDragged

    private void arroz_maizSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arroz_maizSliderMouseDragged
        arroz_maizJTextField.setText(Integer.toString(arroz_maizSlider.getValue()));
    }//GEN-LAST:event_arroz_maizSliderMouseDragged

    private void fgSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgSliderMouseDragged
        fgJTextField.setText(Integer.toString(fgSlider.getValue()));
    }//GEN-LAST:event_fgSliderMouseDragged

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed
        boolean valido = true;
        
        if (this.getAromaSabor1().equals(this.getAromaSabor2())){
            valido = false;
            
            JOptionPane.showMessageDialog(null, "¡Has introducido el mismo"
                    + " valor en 'Aroma / Sabor Primario' y 'Aroma / Sabor Secundario'!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else if ((this.getTrigo() + this.getCenteno() + this.getArrozMaiz()) > 100){
            valido = false;
            
            JOptionPane.showMessageDialog(null, "¡No puede haber mas del"
                    + " 100% del porcentaje de ingredientes!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        if (valido) {
            try {
                Ingredients ingredients = new Ingredients();
                Beer_Styles beerstyle = new Beer_Styles();

                Ingredient ingredient = new Ingredient(this.getTrigo(), this.getCenteno(),
                        this.getArrozMaiz(), this.getUnhopped(), this.getEspecias());

                double[] input = new double[5];
                input[0] = ingredient.getWheat();
                input[1] = ingredient.getRye();
                input[2] = ingredient.getRice_corn();
                input[3] = ingredient.getUnhopped();
                input[4] = ingredient.getSpices();

                ingredient.setResult(ingredients.crispInference(input)[0]);

                String ingredientValue = ingredient.getResult();

                Beer beer = new Beer(this.getColor(), this.getIBU(),
                        this.getOG(), this.getFG(), this.getTransparencia(),
                        this.getFermentacion(), ingredientValue, this.getAromaSabor1(), this.getAromaSabor2());

                double[] finalInput = new double[9];

                finalInput[0] = beer.getColour();
                finalInput[1] = beer.getIbus();
                finalInput[2] = beer.getOg();
                finalInput[3] = beer.getFg();
                finalInput[4] = beer.getTransparency();
                finalInput[5] = beer.getFermentation();
                finalInput[6] = beer.getIngredients();
                finalInput[7] = beer.getFlavor_aroma_1();
                finalInput[8] = beer.getFlavor_aroma_2();

                double [] output = beerstyle.crispInference(finalInput);

                ResultWindow window = new ResultWindow(this, beer.getFinal_beer(output[0]), (int) this.getColor());
                window.setLocationRelativeTo(null);
                window.setVisible(true);
                this.setVisible(false);

            } catch (ImposibleBeer ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void restablecerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restablecerButtonActionPerformed
        colorSlider.setValue(1);
        ibuSlider.setValue(1);
        ogSlider.setValue(1030);
        fgSlider.setValue(1000);
        transparenciaComboBox.setSelectedIndex(0);
        fermentacionComboBox.setSelectedIndex(0);
        trigoSlider.setValue(0);
        centenoSlider.setValue(0);
        arroz_maizSlider.setValue(0);
        unhoppedComboBox.setSelectedIndex(1);
        especiasComboBox.setSelectedIndex(1);
        aroma_sabor_1ComboBox.setSelectedIndex(0);
        aroma_sabor_2ComboBox.setSelectedIndex(0);
        
        initialiceComponents();
        
    }//GEN-LAST:event_restablecerButtonActionPerformed

    private void initialiceComponents() {
        colorJTextField.setText(Integer.toString(colorSlider.getValue()));
        ibuJTextField.setText(Integer.toString(ibuSlider.getValue()));
        ogJTextField.setText(Integer.toString(ogSlider.getValue()));
        fgJTextField.setText(Integer.toString(fgSlider.getValue()));
        trigoJTextField.setText(Integer.toString(trigoSlider.getValue()));
        centenoJTextField.setText(Integer.toString(centenoSlider.getValue()));
        arroz_maizJTextField.setText(Integer.toString(arroz_maizSlider.getValue()));
    
    }
    private void colorSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorSliderMouseClicked
        colorJTextField.setText(Integer.toString(colorSlider.getValue()));
    }//GEN-LAST:event_colorSliderMouseClicked

    private void ibuSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ibuSliderMouseClicked
        ibuJTextField.setText(Integer.toString(ibuSlider.getValue()));
    }//GEN-LAST:event_ibuSliderMouseClicked

    private void ogSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ogSliderMouseClicked
        ogJTextField.setText(Integer.toString(ogSlider.getValue()));
    }//GEN-LAST:event_ogSliderMouseClicked

    private void fgSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fgSliderMouseClicked
        fgJTextField.setText(Integer.toString(fgSlider.getValue()));
    }//GEN-LAST:event_fgSliderMouseClicked

    private void trigoSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trigoSliderMouseClicked
        trigoJTextField.setText(Integer.toString(trigoSlider.getValue()));
    }//GEN-LAST:event_trigoSliderMouseClicked

    private void centenoSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_centenoSliderMouseClicked
        centenoJTextField.setText(Integer.toString(centenoSlider.getValue()));
    }//GEN-LAST:event_centenoSliderMouseClicked

    private void arroz_maizSliderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arroz_maizSliderMouseClicked
        arroz_maizJTextField.setText(Integer.toString(arroz_maizSlider.getValue()));
    }//GEN-LAST:event_arroz_maizSliderMouseClicked

    public double getColor(){
        return colorSlider.getValue();
    }
    
    public double getIBU(){
        return ibuSlider.getValue();
    }
    
    public double getOG(){
        return ogSlider.getValue();
    }
    
    public double getFG(){
        return fgSlider.getValue();
    }
    
    public String getTransparencia(){
        return transparenciaComboBox.getSelectedItem().toString();
    }
    
    public String getFermentacion(){
        return fermentacionComboBox.getSelectedItem().toString();
    }
    
    public double getTrigo(){
        return trigoSlider.getValue();
    }
    
    public double getCenteno(){
        return centenoSlider.getValue();
    }
    
    public double getArrozMaiz(){
        return arroz_maizSlider.getValue();
    }
    
    public boolean getUnhopped(){
        boolean unhopped;
        
        if (unhoppedComboBox.getSelectedItem().toString().equals("Si")) {
            unhopped = true;
        } else {
            unhopped = false;
        }
        
        return unhopped;
    }
    
    public boolean getEspecias(){
        
        boolean spiced;
        
        if (especiasComboBox.getSelectedItem().toString().equals("Si")) {
            spiced = true;
        } else {
            spiced = false;
        }
        
        return spiced;
    }
    
    public String getAromaSabor1(){
        return aroma_sabor_1ComboBox.getSelectedItem().toString();
    }
    
    public String getAromaSabor2(){
        return aroma_sabor_2ComboBox.getSelectedItem().toString();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JComboBox aroma_sabor_1ComboBox;
    private javax.swing.JComboBox aroma_sabor_2ComboBox;
    private javax.swing.JTextField arroz_maizJTextField;
    private javax.swing.JSlider arroz_maizSlider;
    private javax.swing.JTextArea ayudajTextArea;
    private javax.swing.JTextField centenoJTextField;
    private javax.swing.JSlider centenoSlider;
    private javax.swing.JTextField colorJTextField;
    private javax.swing.JSlider colorSlider;
    private javax.swing.JComboBox especiasComboBox;
    private javax.swing.JComboBox fermentacionComboBox;
    private javax.swing.JTextField fgJTextField;
    private javax.swing.JSlider fgSlider;
    private javax.swing.JTextField ibuJTextField;
    private javax.swing.JSlider ibuSlider;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel jpanel0;
    private javax.swing.JTextField ogJTextField;
    private javax.swing.JSlider ogSlider;
    private javax.swing.JButton restablecerButton;
    private javax.swing.JComboBox transparenciaComboBox;
    private javax.swing.JTextField trigoJTextField;
    private javax.swing.JSlider trigoSlider;
    private javax.swing.JComboBox unhoppedComboBox;
    // End of variables declaration//GEN-END:variables
}
